version: '3.7'

services:
    rancher:
        image: rancher/rancher:${VERSION}
        container_name: rancher
        restart: unless-stopped
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - rancher-data:/var/lib/rancher
        command: --acme-domain ${DOMAIN}
    
volumes:
    rancher-data:
        external: true
