version: '3.7'

services:
    rancher:
        image: rancher/rancher:latest
        container_name: rancher
        restart: unless-stopped
        ports:
          - "80:80"
          - "443:443"
        command: --acme-domain rancher.brosy.dev
    
